[package]
name = "cli"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
description = "A command-line interface for Kolibrie"

[dependencies]
clap = { workspace = true }
kolibrie = { path = "../kolibrie" }

[features]
default = []
ml = ["kolibrie/ml"]

[lints]
workspace = true
