[package]
name = "datalog"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
description = "Datalog Engine"

[dependencies]
nom = { workspace = true }
shared = { path = "../shared" }
rayon = { workspace = true }

[dev-dependencies]
shared = { path = "../shared" }

[lints]
workspace = true
