[package]
name = "kolibrie-python"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
description = "Python Binding"

[lib]
name = "kolibrie"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module", "abi3-py310"] }
datalog = { path = "../datalog" }
shared = { path = "../shared" }
kolibrie_core = { package = "kolibrie", path = "../kolibrie" }

[features]
default = []
ml = ["kolibrie_core/ml"]

[lints]
workspace = true
