[package]
name = "datalogmtl"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[dependencies]
shared  = { path = "../shared" }
datalog = { path = "../datalog" }
serde   = { workspace = true }
rayon   = { workspace = true }

[lints]
workspace = true
