[package]
name = "kolibrie-http-server"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[dependencies]
kolibrie = { path = "../kolibrie" }
datalog =  { path = "../datalog" }
datalogmtl = { path = "../datalogmtl" }
shared = { path = "../shared" }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
ml = ["kolibrie/ml"]

[lints]
workspace = true
